### ISSUE TITLE
Change to resourceinfo.exe or formats?

### ISSUE THREAD

**Issue by tranek** [RobinKa/source_2_resource_decompiler#1]
Hello,

I tried the decompiler on the particles but it is just returning a text file with only

`<!-- schema text {7e125a45-3d83-4043-b292-9e24f8ef27b4} generic {198980d8-3a93-4919-b4c6-dd1fb07a3a4b} -->`

So I just tried using the `resourceinfo.exe` by itself to get info about the `.vpcf_c` file and it's erroring:

`Unable to determine mod from file aegis_respawn.vpcf_c`

It has this same error for all `.vpcf_c`, `vmdl_c`, `.vmat_c`, and `.vtex_c` files. Did I miss some important instruction on how to use `resourceinfo.exe`? Or maybe Valve changed it or the file formats recently since you last tested it? Are you getting this error?

Thanks

**Comment by RobinKa** [comment]
Hey tranek,

They might have changed it, I'll check it out when I have time thanks for letting me know!

~Toraxxx

**Comment by tranek** [comment]
Great, thank you! Let me know if I can help in any way.

Also, are you planning to extend this to the other compiled formats? `.vmdl_c`, `.vmat_c`, and `.vtex_c`?

**Comment by RobinKa** [comment]
I have looked into them, but most of them are far more complicated than the particle format so I didn't want to spend so much time on them.

**Comment by RobinKa** [comment]
You need to put the vpcf_c into the same folder in your Dota2 directory as where you extracted it from 

Quote from the readme:

Extract the .vpcf_c that you want into the same corresponding path in dota_imported For example if a particle is in /particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf_c it will go into dota 2 beta/dota_ugc/game/dota_imported/particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf_c

**Comment by tranek** [comment]
Ah, my mistake. Weird that it works like that. Thank you!
